### ISSUE TITLE
ModuleNotFoundError: No module named 'config'

### ISSUE THREAD

**Issue by liuzheng081** [grasses/Tampering-Detection-and-Localization#1]
Hi,
i download the model and run "python main.py --conf code.config --action test" code in the root of 
Tampering-Detection-and-Localization, but error **ModuleNotFoundError: No module named 'config'**

Traceback (most recent call last):
  File "main.py", line 124, in <module>
    main()
  File "main.py", line 63, in main
    conf = __import__(args.conf, globals(), locals(), ["Config"]).Config
  File "/home/×××/Tampering-Detection-and-Localization/code/__init__.py", line 8, in <module>
    from config import Config
ModuleNotFoundError: No module named 'config'

Can you help me how to fix this error

**Comment by grasses** [comment]
This error comes from different Python versions, I have updated the code.
I run the project using Python2.7.15.

**Comment by liuzheng081** [comment]
> This error comes from different Python versions, I have updated the code.
> I run the project using Python2.7.15.

Thank you
and i will try with python2.7  .

**Comment by liuzheng081** [comment]
> > This error comes from different Python versions, I have updated the code.
> > I run the project using Python2.7.15.
> 
> Thank you
> and i will try with python2.7 .

Hi，
i run the "python main.py --code.config --action test" with python2.7 and use model **dresden.model5**.And i got this 
![image](https://user-images.githubusercontent.com/10113362/54510438-3845f700-4988-11e9-97f7-3e8b33b69e11.png)
and i wonder to know about 
![image](https://user-images.githubusercontent.com/10113362/54510487-6deae000-4988-11e9-9fe0-51921a9c9049.png)
how to do with step 3? 
i try to run the **experiment/2-1.ipynb**  with jupyter notebook. and change the root_path and scope_name
![image](https://user-images.githubusercontent.com/10113362/54510614-0ed99b00-4989-11e9-8355-bd9d1091ba32.png)
but i could not get the reuslt as same sa yours. 
Am i loss something?
And i got the model that you have uploaded. How can I use this model to do some test whit my own tampered image??

**Comment by grasses** [comment]
The project adopts two steps running strategy:
1. Running CNN and extracting patches features, the results return as a list of csv files.
2. Fusing patches result using "Reliability Fusing Map (RFM)" to obtain a tampering map for an inspected image.

The output csv is in folder of `./Tampering-Detection-and-Localization/code/model/{scope_name}/pre-train`, you should replace the path in second step experiments.
