### ISSUE TITLE
模型准确率如何？

### ISSUE THREAD

**Issue by uulucky** [grasses/Tampering-Detection-and-Localization#4]
代码跑不通，请问大神准确率如何，小弟正在学习这个呢
1、是否会把正常照片识别为篡改？
2、用手机给篡改的照片拍张照片，是否还能识别出来篡改？
请在百忙之中回复一下，不胜感激。鸡犬升天。天道酬勤。

**Comment by xxllp** [comment]
m

**Comment by grasses** [comment]
见paper：https://github.com/grasses/Tampering-Detection-and-Localization/blob/master/paper_RFM.pdf
