### ISSUE TITLE
I can't download model from Baidu

### ISSUE THREAD

**Issue by ibarbech** [grasses/Tampering-Detection-and-Localization#9]
Hello.

Thanks for share your project. 
I'm from spain and baidu is not available for spain, there aren't any way for download your model from baidu.

Can you share the model with me via google drive or similar please?

Thanks for your attention.

**Comment by grasses** [comment]
https://drive.google.com/file/d/1ULTmA1Ef5Y8NcOc1bSF8Ksj7rapaN0zO/view?usp=sharing

**Comment by ibarbech** [comment]
Thanks for share it with me. But the link isn't public.
Can you change link's properties for anyone can access?
